### ISSUE TITLE
[BUG] When ran in Docker `.update` always says updates available but always fails to update 

### ISSUE THREAD

**Issue by androidacy-user** [AvinashReddy3108/PaperplaneExtended#12]
**Describe the bug**
Updater works incorrectly in Docker 

**To Reproduce**
1. Run `.update`
2. See says update available when you just freshly cloned this repo
3. Run `.update now`
4. Hangs

**Expected behavior**
It to show correct updates info and to update as needed 

**Screenshots**
N/A

**Python Version**
3.6.8

**Additional context**
Ubuntu 18.04.2 w/ latest Docker

**Comment by AvinashReddy3108** [comment]
Maybe that's beacuse of the Docker's ephemeral filesystem ?

**Comment by xAbdaziz** [comment]
Hi, I'm having the same issue as well in docker.
Here are the logs:

```Disclaimer:
This file uploaded ONLY here,
we logged only fact of error and date,
we respect your privacy,
you may not report this error if you've
any confidential data here, no one will see your data

--------BEGIN USERBOT TRACEBACK LOG--------
Date: 2019-09-22 18:33:17
Group ID: ********
Sender ID: *******

Event Trigger:
.update now

Traceback info:
Traceback (most recent call last):
  File "/usr/lib/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/usr/lib/python3.7/collections/__init__.py", line 916, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.7/collections/__init__.py", line 908, in __missing__
    raise KeyError(key)
KeyError: 'git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/git/remote.py", line 428, in __getattr__
    return self._config_reader.get(attr)
  File "/usr/lib/python3.7/site-packages/git/config.py", line 124, in <lambda>
    return lambda *args, **kwargs: self._call_config(attr, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/git/config.py", line 130, in _call_config
    return getattr(self._config, method)(self._section_name, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/git/config.py", line 79, in assure_data_present
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'git' in section: 'remote "upstream"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/userbot/userbot/userbot/events.py", line 45, in wrapper
    await func(errors)
  File "/home/userbot/userbot/userbot/modules/updater.py", line 103, in upstream
    ups_rem.git.reset('--hard', 'FETCH_HEAD')
  File "/usr/lib/python3.7/site-packages/git/remote.py", line 430, in __getattr__
    return super(Remote, self).__getattr__(attr)
  File "/usr/lib/python3.7/site-packages/gitdb/util.py", line 255, in __getattr__
    return object.__getattribute__(self, attr)
AttributeError: 'Remote' object has no attribute 'git'


Error text:
'Remote' object has no attribute 'git'

--------END USERBOT TRACEBACK LOG--------


Last 5 commits:
Avinash Reddy: Non Spammy PMPermit - Fixes```
